#inputs for main Snakefile
sras: "/path/to/sm_Bioproj2Lineage/dirTemplate/batchedtsvs/PRJNA736718_batch23_sras.tsv"
reference: "/path/to/A_01_downloadAlign/NC_000962_3.fa"
wanted_lineage: "lineage4.8"
basedir: "/path/to/sm_Bioproj2Lineage/dirTemplate/sm_Accs2Runaccs"