#inputs for main Snakefile
#sras: "data/SRAs.tsv"
reference: "/path/to/A_01_downloadAlign/NC_000962_3.fa"
wanted_lineage: "lineage4.8"

#inputs for snakemake rules to get fastq
alljson: "/path/to/sm_Accs2Runaccs/json_summarise/js_summarise_dummy.tsv"

